#!/bin/bash

cd `dirname $0`/..

source script/setup_classpath.sh

BROWSE_URL="(browse-url \"http://localhost:8080/development\")"
if [[ -n "$1" ]]; then
    BROWSE_URL="(binding [*open-url-script* \"$1\"] $BROWSE_URL)"
fi

java -server -cp $CLJSC_CP jline.ConsoleRunner clojure.main -e \
"(use '[one.sample.dev-server :only (run-server cljs-repl)])
 (use '[clojure.java.browse :only (browse-url *open-url-script*)])
 (run-server)
 (future (Thread/sleep 3000) $BROWSE_URL)
 (cljs-repl)" --repl

